IF OBJECT_ID (N'FN_BOYEAR') IS NOT NULL
    DROP FUNCTION FN_BOYEAR;
GO

CREATE FUNCTION FN_BOYEAR 
(
    @Date DATE
)
RETURNS DATE
AS
BEGIN
    DECLARE @Result DATE = DATEFROMPARTS(YEAR(@Date),1,1)
 
    RETURN @Result;
END
GO