IF OBJECT_ID (N'FN_BOQUARTER') IS NOT NULL
    DROP FUNCTION FN_BOQUARTER;
GO

CREATE FUNCTION FN_BOQUARTER 
(
    @Date DATE
)
RETURNS DATE
AS
BEGIN

    DECLARE @Result DATE = DATEFROMPARTS(YEAR(@Date),DATEPART(quarter,@Date) * 3 - 2,1);

    RETURN @Result;
END
GO