IF OBJECT_ID (N'FN_EOYEAR') IS NOT NULL
   DROP FUNCTION FN_EOYEAR;
GO

CREATE FUNCTION FN_EOYEAR (@Date DATE)
RETURNS DATE
AS
BEGIN
     DECLARE @Result DATE = DATEADD(day,-1,DATEFROMPARTS(YEAR(@Date)+1,1,1));
	 
	 RETURN @Result;
END
GO