IF OBJECT_ID (N'FN_EOMONTH') IS NOT NULL
   DROP FUNCTION FN_EOMONTH;
GO

CREATE FUNCTION FN_EOMONTH (@Date DATE)
RETURNS DATE
AS
BEGIN
     DECLARE @Result DATE = DATEADD(day,-1,DATEFROMPARTS(YEAR(@Date),MONTH(@Date)+1,1))
	 
	 RETURN @Result;
END
GO